<a href="https://colab.research.google.com/github/krithikasowmya/python-codes-/blob/main/python_sessions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = 20
b = 3
result =a % b
print("Remainder:",result)

Remainder: 2


In [1]:
'Krithika'

'Krithika'

In [2]:
print('krithika')

krithika


In [3]:
print("krithika's system")

krithika's system


In [5]:
'krithi' + 'krithi'

'krithikrithi'

In [6]:
6*'krithi'

'krithikrithikrithikrithikrithikrithi'

In [7]:
print('krithika\nsystem')

krithika
system


In [8]:
a = 10
b = 5
result = a + b
print("Addition:", result)

Addition: 15


In [9]:
a = 15
b = 7
result = a - b
print("Subtraction:", result)

Subtraction: 8


In [4]:
print("krithika 'system'")

krithika 'system'


In [10]:
a = 4
b = 6
result = a * b
print("Multiplication:", result)

Multiplication: 24


In [11]:
a = 20
b = 4
result = a / b  # gives decimal value
print("Division:", result)

Division: 5.0


In [12]:
a = 20
b = 3
result = a // b  # gives only the whole number part
print("Integer Division:", result)

Integer Division: 6


In [13]:
a = 20
b = 3
result = a % b  # gives the remainder
print("Remainder:", result)

Remainder: 2


In [14]:
a = 2
b = 3
result = a ** b  # 2 to the power 3 = 8
print("Power:", result)

Power: 8


In [16]:
name = "krithika"
age = 19
print("My name is", name, "and I am", age, "years old.")

My name is krithika and I am 19 years old.


In [17]:
name = "Alice"

# Accessing individual characters using indexing
print(name[0])  # First character
print(name[1])  # Second character
print(name[-3]) # Last character


A
l
i


In [18]:
name = "Alice"

# Slicing means cutting a part of the string
print(name[0:3])  # From index 0 to 2 (not including 3)
print(name[:4])   # From start to index 3
print(name[2:])   # From index 2 to end

Ali
Alic
ice


In [19]:
first_name = "Alice"
last_name = "Smith"

# Combine with + operator
full_name = first_name + " " + last_name
print(full_name)

Alice Smith


In [20]:
message = "Hello, world!"
print(len(message))

13


In [21]:
text = "Python"

print(text.upper())  # ALL CAPS
print(text.lower())  # all lowercase

PYTHON
python


In [22]:
message = "I like apples"
new_message = message.replace("apples", "mangoes")
print(new_message)

I like mangoes


In [23]:
text = "   Hello world!   "
cleaned = text.strip()
print("Before:", text)
print("After:", cleaned)

Before:    Hello world!   
After: Hello world!


In [24]:
name = "Alice"
age = 10

# Convert number to string before combining
message = name + " is " + str(age) + " years old."
print(message)

Alice is 10 years old.


In [25]:
# List of numbers
numbers = [10, 20, 30, 40]

# List of strings
fruits = ["apple", "banana", "mango"]

# Mixed data types
mixed = ["Alice", 25, True]

In [26]:
fruits = ["apple", "banana", "mango"]

print(fruits[0])  # First item
print(fruits[1])  # Second item
print(fruits[2]) # Last item

apple
banana
mango


In [27]:
fruits = ["apple", "banana", "mango", "orange", "grape"]

print(fruits[1:4])  # banana to orange
print(fruits[:3])   # apple to mango
print(fruits[2:])   # mango to end

['banana', 'mango', 'orange']
['apple', 'banana', 'mango']
['mango', 'orange', 'grape']


In [28]:
fruits = ["apple", "banana"]
fruits.append("mango")
print(fruits)

['apple', 'banana', 'mango']


In [29]:
fruits = ["apple", "banana"]
fruits.insert(1, "grape")  # Add at index 1
print(fruits)

['apple', 'grape', 'banana']


In [30]:
fruits = ["apple", "banana", "apple"]
fruits.remove("apple")  # Removes first 'apple'
print(fruits)

['banana', 'apple']


In [31]:
fruits = ["apple", "banana", "mango"]
fruits.pop()
print(fruits)

['apple', 'banana']


In [32]:
fruits = ["apple", "banana"]
fruits.clear()
print(fruits)  # Output: []

[]


In [33]:
numbers = [5, 2, 8, 1]
numbers.sort()
print(numbers)

[1, 2, 5, 8]


In [34]:
fruits = ["apple", "banana", "mango"]
fruits.reverse()
print(fruits)

['mango', 'banana', 'apple']


In [35]:
fruits = ["apple", "banana", "mango"]
print(len(fruits))

3


In [36]:
numbers = [5, 12, 3, 8]
print(max(numbers))  # 12
print(min(numbers))  # 3
print(sum(numbers))  # 28

12
3
28


In [37]:
fruits = ["apple", "banana"]
print("apple" in fruits)   # True
print("grape" in fruits)   # False

True
False


In [39]:
my_tuple = ("apple", "banana", "cherry")
print(my_tuple)

('apple', 'banana', 'cherry')


In [40]:
my_tuple = ("apple", "banana", "cherry")

# Indexing
print(my_tuple[0])  # apple
print(my_tuple[-1]) # cherry

# Slicing
print(my_tuple[0:2])  # ('apple', 'banana')

apple
cherry
('apple', 'banana')


In [41]:
my_tuple = ("apple", "banana", "apple", "cherry")

# count() – how many times a value appears
print(my_tuple.count("apple"))  # 2

# index() – find the position of a value
print(my_tuple.index("cherry"))  # 3

2
3


In [42]:
my_set = {"apple", "banana", "cherry"}
print(my_set)

{'cherry', 'banana', 'apple'}


In [43]:
dup_set = {"apple", "banana", "apple"}
print(dup_set)  # Output: {'apple', 'banana'}

{'banana', 'apple'}


In [44]:
fruits = {"apple", "banana", "grapes"}

fruits.clear()
print(fruits)  # Output: set()

set()


In [45]:
set1 = {"apple", "banana"}
set2 = {"mango", "banana"}

combined = set2.union(set1)
print(combined)  # {'apple', 'banana', 'mango'}

{'banana', 'apple', 'mango'}


In [46]:
set1 = {"apple", "banana"}
set2 = {"mango", "banana"}
common = set1.intersection(set2)
print(common)  # {'banana'}

{'banana'}


In [47]:
student = {
    "name": "Alice",
    "age": 21,
    "grade": "A"
}
print(student)

{'name': 'Alice', 'age': 21, 'grade': 'A'}


In [48]:
print(student["name"])   # Alice
print(student["age"])    # 21

Alice
21


In [49]:
print(student.get("grade"))     # A
print(student.get("marks"))     # None (no error)
print(student.get("marks", 10))  # 0 (default value)

A
None
10


In [50]:
student["marks"] = 85           # Add new key
student["grade"] = "A+"         # Update value
print(student)

{'name': 'Alice', 'age': 21, 'grade': 'A+', 'marks': 85}


In [51]:
student.pop("age")              # Removes the key 'age'
print(student)

{'name': 'Alice', 'grade': 'A+', 'marks': 85}


In [52]:
for key in student:
    print(key, ":", student[key])

name : Alice
grade : A+
marks : 85


In [53]:
for key, value in student.items():
    print(key, "=>", value)

name => Alice
grade => A+
marks => 85


In [54]:
keys = ["name", "age", "grade"]
values = ["Bob", 22, "B"]

student2 = dict(zip(keys, values))
print(student2)

{'name': 'Bob', 'age': 22, 'grade': 'B'}


In [55]:
classroom = {
    "student1": {"name": "tom", "marks": 90},
    "student2": {"name": "Bob", "marks": 85}
}

print(classroom["student1"])                # {'name': 'Alice', 'marks': 90}
print(classroom["student1"]["marks"])       # 90


{'name': 'tom', 'marks': 90}
90


In [56]:
x = 5
print(type(x))  # Output: <class 'int'>

<class 'int'>


In [57]:
b = 3.14
print(type(b))  # <class 'float'>

<class 'float'>


In [58]:
c = 3 + 2j
print(type(c))

<class 'complex'>


In [59]:
text = "Hello World"
print(type(text))   # <class 'str'>

<class 'str'>


In [60]:
is_active = True
print(type(is_active))  # <class 'bool'>

<class 'bool'>


In [61]:
fruits = ["apple", "banana", "mango"]
print(type(fruits))  # <class 'list'>

<class 'list'>


In [62]:
coordinates = (10, 20)
print(type(coordinates))  # <class 'tuple'>

<class 'tuple'>


In [63]:
numbers = range(5)
print(list(numbers))  # [0, 1, 2, 3, 4]

[0, 1, 2, 3, 4]


In [64]:
colors = {"red", "blue", "green", "red"}
print(colors)  # {'red', 'blue', 'green'}

{'blue', 'red', 'green'}


In [65]:
person = {"name": "Alice", "age": 22}
print(person["name"])  # Alice
print(type(person))

Alice
<class 'dict'>


In [66]:
x = 5
y = float(x)         # 5.0
z = str(x)           # "5"
a = int("10")        # 10
b = list("abc")      # ['a', 'b', 'c']

In [67]:
a = 10
b = str(a)
print(b, type(b))    # "10", <class 'str'>

c = "123"
d = int(c)
print(d, type(d))

10 <class 'str'>
123 <class 'int'>


In [68]:
a = 10
b = 3

print("Addition:", a + b)        # 13
print("Subtraction:", a - b)     # 7
print("Multiplication:", a * b)  # 30
print("Division:", a / b)        # 3.333...
print("Floor Division:", a // b) # 3
print("Modulus:", a % b)         # 1
print("Power:", a ** b)

Addition: 13
Subtraction: 7
Multiplication: 30
Division: 3.3333333333333335
Floor Division: 3
Modulus: 1
Power: 1000


In [69]:
x = 5           # Simple assignment
x += 3          # x = x + 3 => 8
x *= 2          # x = x * 2 => 16
x -= 4          # x = x - 4 => 12
print(x)        # Output: 12

# Assign multiple variables at once
a, b = 10, 20
print(a, b)     # 10 20

12
10 20


In [70]:
a = 5
b = 7

print(a == b)  # False
print(a != b)  # True
print(a > b)   # False
print(a < b)   # True
print(a >= 5)  # True
print(a <= 3)  # False

False
True
False
True
True
False


In [71]:
n = 5
print(-n)     # -5
print(+n)     # 5

flag = True
print(not flag)   # False (negates the value)

-5
5
False


In [72]:
a = 10
b = 20

# and operator
print(a > 5 and b > 15)   # True (both True)
print(a > 15 and b > 15)  # False

# or operator
print(a > 15 or b > 15)   # True (one is True)
print(a > 5 or b < 15)    # False (both False)

# not operator
x = True
y = False
print(not x)  # False
print(not y)  # True

True
False
True
True
False
True


In [73]:
number = 345
print("Decimal number:", number)

Decimal number: 345


In [74]:
# Decimal to Binary
decimal = 51
binary = bin(decimal)
print("Binary of 51 is:", binary)  # Output: 0b110011

# Binary to Decimal
binary_value = "0b110011"
decimal_back = int(binary_value, 2)
print("Binary '0b110011' to decimal:", decimal_back)

Binary of 51 is: 0b110011
Binary '0b110011' to decimal: 51


In [75]:
# Decimal to Octal
decimal = 51
octal = oct(decimal)
print("Octal of 51 is:", octal)  # Output: 0o63

# Octal to Decimal
octal_value = "0o63"
decimal_back = int(octal_value, 8)
print("Octal '0o63' to decimal:", decimal_back)

Octal of 51 is: 0o63
Octal '0o63' to decimal: 51


In [76]:
# Decimal to Hexadecimal
decimal = 51
hexa = hex(decimal)
print("Hexadecimal of 51 is:", hexa)  # Output: 0x33

# Hexadecimal to Decimal
hex_value = "0x33"
decimal_back = int(hex_value, 16)
print("Hexadecimal '0x33' to decimal:", decimal_back)

Hexadecimal of 51 is: 0x33
Hexadecimal '0x33' to decimal: 51


In [77]:
binary_str = '11011'
decimal = int(binary_str, 2)
print("Binary 11011 to Decimal:", decimal)  # Output: 27

Binary 11011 to Decimal: 27


In [78]:
octal_str = '360'
decimal = int(octal_str, 8)
print("Octal 360 to Decimal:", decimal)  # Output: 240

Octal 360 to Decimal: 240


In [79]:
hex_str = '33'
decimal = int(hex_str, 16)
print("Hexadecimal 33 to Decimal:", decimal)  # Output: 51

Hexadecimal 33 to Decimal: 51


In [80]:
octal = "725"
binary = ''.join([bin(int(digit))[2:].zfill(3) for digit in octal])
print("Octal 725 to Binary:", binary)  # Output: 111010101

Octal 725 to Binary: 111010101


In [81]:
binary = '101011011'
# Pad the binary string to a multiple of 3
while len(binary) % 3 != 0:
    binary = '0' + binary
octal = ''
for i in range(0, len(binary), 3):
    octal += str(int(binary[i:i+3], 2))
print("Binary 101011011 to Octal:", octal)  # Output: 533

Binary 101011011 to Octal: 533


In [82]:
a = 10  # binary: 1010
b = 4   # binary: 0100

In [83]:
result = a & b
print(result)  # Output: 0

0


In [84]:
result = a | b
print(result)  # Output: 14

14


In [85]:
result = a ^ b
print(result)  # Output: 14

14


In [86]:
x = 5
result = ~x
print(result)  # Output: -6

-6


In [87]:
a = 5
result = a << 1
print(result)  # Output: 10

10


In [88]:
a = 20
result = a >> 2
print(result)  # Output: 5

5


In [89]:
a = 10
b = 4
print("a & b =", a & b)   # AND
print("a | b =", a | b)   # OR
print("a ^ b =", a ^ b)   # XOR
print("~a =", ~a)         # NOT
print("a << 1 =", a << 1) # Left Shift
print("a >> 1 =", a >> 1) # Right Shift

a & b = 0
a | b = 14
a ^ b = 14
~a = -11
a << 1 = 20
a >> 1 = 5


In [90]:
x = 7
y = 3
print("x & y =", x & y)
print("x | y =", x | y)
print("x ^ y =", x ^ y)
print("~x =", ~x)
print("x << 2 =", x << 2)
print("x >> 2 =", x >> 2)

x & y = 3
x | y = 7
x ^ y = 4
~x = -8
x << 2 = 28
x >> 2 = 1


In [91]:
import math
print("Square root of 25 is:", math.sqrt(25))  # Output: 5.0

Square root of 25 is: 5.0


In [92]:
print("2 raised to power 3 is:", math.pow(2, 3))  # Output: 8.0


2 raised to power 3 is: 8.0


In [93]:
print("Floor of 3.7 is:", math.floor(3.7))  # Output: 3
print("Ceil of 3.7 is:", math.ceil(3.7))    # Output: 4


Floor of 3.7 is: 3
Ceil of 3.7 is: 4


In [94]:
print("Exponential of 2 is:", math.exp(2))  # Output: e^2 ≈ 7.389


Exponential of 2 is: 7.38905609893065


In [95]:
print("Exponential of 2 is:", math.exp(2))  # Output: e^2 ≈ 7.389


Exponential of 2 is: 7.38905609893065


In [96]:
print("Value of pi is:", math.pi)
print("Value of e is:", math.e)
print("Positive infinity:", math.inf)
print("Not a number (NaN):", math.nan)


Value of pi is: 3.141592653589793
Value of e is: 2.718281828459045
Positive infinity: inf
Not a number (NaN): nan


In [97]:
radius = 5
area = math.pi * radius * radius
print("Area of circle:", area)


Area of circle: 78.53981633974483


In [99]:
radius = 7
area = math.pi * radius ** 2
circumference = 2 * math.pi * radius
print("Area:", area)
print("Circumference:", circumference)


Area: 153.93804002589985
Circumference: 43.982297150257104


In [100]:
#2. Convert degrees to radians and vice versa
degrees = 180
radians = math.radians(degrees)
print("180 degrees in radians:", radians)

# Convert back
deg = math.degrees(radians)
print("Converted back to degrees:", deg)


180 degrees in radians: 3.141592653589793
Converted back to degrees: 180.0


In [101]:
a = 5
b = 6
a = b
print("a:", a)  # Output: 6
print("b:", b)  # Output: 6 => We lost the original value of `a`
a = 5
b = 6
temp = a     # Store the value of a
a = b        # Assign b to a
b = temp     # Restore the original a into b

print("a:", a)  # Output: 6
print("b:", b)  # Output: 5



a: 6
b: 6
a: 6
b: 5


In [102]:
a = 5
b = 6
temp = a     # Store the value of a
a = b        # Assign b to a
b = temp     # Restore the original a into b

print("a:", a)  # Output: 6
print("b:", b)  # Output: 5


a: 6
b: 5


In [104]:
a = 5
b = 6

a = a + b  # a becomes 11
b = a - b  # b becomes 5 (11 - 6)
a = a - b  # a becomes 6 (11 - 5)

print("a:", a)  # Output: 6
print("b:", b)  # Output: 5


a: 6
b: 5


In [105]:
a = 5
b = 6

a = a ^ b
b = a ^ b
a = a ^ b

print("a:", a)  # Output: 6
print("b:", b)  # Output: 5


a: 6
b: 5


In [106]:
a = 5
b = 6

a, b = b, a

print("a:", a)  # Output: 6
print("b:", b)  # Output: 5


a: 6
b: 5


In [107]:
age = 18

if age >= 18:
    print("You are eligible to vote.")


You are eligible to vote.


In [108]:
if True:

 print("This will give an error.")  # ❌ Wrong indentation

This will give an error.


In [109]:
marks = 45

if marks >= 50:
    print("You passed the exam.")
else:
    print("You failed the exam.")


You failed the exam.


In [110]:
num = 15

if num > 0:
    print("Positive number")
    if num % 5 == 0:
        print("Divisible by 5")

Positive number
Divisible by 5


In [111]:
temperature = 30

if temperature > 35:
    print("It's very hot")
elif temperature > 25:
    print("It's warm")
elif temperature > 15:
    print("It's pleasant")
else:
    print("It's cold")


It's warm


In [112]:
temperature = 30

if temperature > 35:
    print("It's very hot")
elif temperature > 25:
    print("It's warm")
elif temperature > 15:
    print("It's pleasant")
else:
    print("It's cold")


It's warm


In [113]:
# Print numbers from 1 to 5 using while loop

count = 1  # Initialization
while count <= 5:  # Condition
    print("Count is:", count)
    count += 1  # Increment


Count is: 1
Count is: 2
Count is: 3
Count is: 4
Count is: 5


In [114]:
# Print numbers 1 to 5 in the same line
count = 1
while count <= 5:
    print(count, end=" \n ")  # Space instead of newline
    count += 1


1 
 2 
 3 
 4 
 5 
 

In [115]:
# Nested while loop to print a pattern
i = 1
while i <= 3:
    j = 1
    while j <= i:
        print("*", end=" ")
        j += 1
    print()  # For new line after each row
    i += 1


* 
* * 
* * * 


In [116]:
# Sum of first 10 natural numbers
n = 1
total = 0

while n <= 10:
    total += n
    n += 1

print("Sum is:", total)

Sum is: 55


In [117]:
for i in range(1, 6):
    if i == 3:
        break
    print(i)


1
2


In [118]:
for i in range(1, 6):
    if i == 3:
        continue
    print(i)


1
2
4
5


In [120]:
for i in range(1, 5):
    if i == 3:
        pass
    else:
        print(i)

1
2
4


In [121]:
print("#")
print("#")
print("#")


#
#
#


In [122]:
print("#", end=" ")
print("#", end=" ")
print("#", end=" ")


# # # 

In [123]:
for i in range(5):
    print("#", end=" ")

# # # # # 

In [124]:
for row in range(4):            # Outer loop = rows
    for col in range(4):        # Inner loop = columns
        print("#", end=" ")
    print()                     # Moves to the next line after each row


# # # # 
# # # # 
# # # # 
# # # # 


In [ ]:
for i in range(1, 6):              # i = current row
    for j in range(i):            # print j times per row
        print("#", end=" ")
    print()                       # move to next line


In [ ]:
for i in range(5):               # i = 0 to 4
    for j in range(5 - i):       # print (5 - i) hashes
        print("#", end=" ")
    print()


In [125]:
import array as arr


In [126]:
numbers = arr.array('i', [10, 20, 30, 40, 50])

In [127]:
print(numbers.buffer_info())


(136701333819152, 5)


In [128]:
print(numbers.typecode)

i


In [129]:
numbers.append(60)
print(numbers)


array('i', [10, 20, 30, 40, 50, 60])


In [130]:
numbers.reverse()
print(numbers)


array('i', [60, 50, 40, 30, 20, 10])


In [131]:
print(numbers[0])  # First element
print(numbers[2])  # Third element


60
40


In [132]:
for num in numbers:
    print(num)

60
50
40
30
20
10


In [133]:
i = 0
while i < len(numbers):
    print(numbers[i])
    i += 1

60
50
40
30
20
10


In [134]:
new_array = arr.array('i', [])

for value in numbers:
    new_array.append(value)

print("New Array:", new_array)

New Array: array('i', [60, 50, 40, 30, 20, 10])


In [135]:
from numpy import *
mat = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mat)
print('First row:', mat[0])
print('Element at (2,3):', mat[1][2])
print('All rows of 2nd column:', mat[:, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
Element at (2,3): 6
All rows of 2nd column: [2 5 8]


In [136]:
from numpy import *

# 1. array() - creates array from a list
arr1 = array([1, 2, 3, 4])
print("Array:", arr1)
print("Type:", arr1.dtype)

# 2. linspace() - creates array with equal intervals
arr2 = linspace(0, 10, 5)  # divides from 0 to 10 in 5 parts
print("\nLinspace:", arr2)

# 3. arange() - works like range()
arr3 = arange(1, 10, 2)  # starts from 1, goes till <10, step = 2
print("\nArange:", arr3)

# 4. logspace() - spaced numbers on a log scale
arr4 = logspace(1, 3, 5)  # 10^1 to 10^3 in 5 parts
print("\nLogspace:", arr4)

# 5. zeros() - creates array of 0s
arr5 = zeros(5)
print("\nZeros:", arr5)

# 6. ones() - creates array of 1s
arr6 = ones(4, int)
print("\nOnes (int):", arr6)


Array: [1 2 3 4]
Type: int64

Linspace: [ 0.   2.5  5.   7.5 10. ]

Arange: [1 3 5 7 9]

Logspace: [  10.           31.6227766   100.          316.22776602 1000.        ]

Zeros: [0. 0. 0. 0. 0.]

Ones (int): [1 1 1 1]


In [137]:
from numpy import *

# Matrix with 2 rows and 3 columns
matrix = array([[1, 2, 3],
                [4, 5, 6]])
print("Matrix:\n", matrix)


Matrix:
 [[1 2 3]
 [4 5 6]]


In [138]:
# Access 1st row, 2nd column (remember: index starts at 0)
print("Element at (0,1):", matrix[0][1])  # Output: 2

# Access entire row
print("First row:", matrix[0])

# Access entire column
print("Second column:", matrix[:,1])


Element at (0,1): 2
First row: [1 2 3]
Second column: [2 5]


In [139]:
# Print all elements using nested loops
for row in matrix:
    for item in row:
        print(item, end=" ")
    print()


1 2 3 
4 5 6 


In [140]:
from numpy import *

mat = array([[1, 2, 3],
             [4, 5, 6]])

# Shape = (rows, columns)
print("Shape:", mat.shape)

# Reshape 2x3 to 3x2
reshaped = mat.reshape(3, 2)
print("Reshaped to 3x2:\n", reshaped)

# Flatten matrix (2D → 1D)
flat = mat.flatten()
print("Flattened:", flat)

Shape: (2, 3)
Reshaped to 3x2:
 [[1 2]
 [3 4]
 [5 6]]
Flattened: [1 2 3 4 5 6]
